# Generated by Django 4.1.7 on 2023-08-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sotck',
            new_name='stock',
        ),
    ]
